version: "3.9"
services:

  db-local:
    image: "postgres:13.10-alpine"
    container_name: pysect-backend-db-local
    restart: unless-stopped
    volumes:
      - pgdata-local:/var/lib/postgresql/data
    networks:
      - pysect-network
    ports:
      - "9001:5432"
    env_file:
      - ./docker/config/.env.local

  redis-local:
    image: redis:latest
    container_name: pysect-backend-redis-local
    ports:
      - "9002:6379"
    networks:
      - pysect-network

  web-local:
    image: "pysect-backend-challenge-local"
    container_name: pysect-backend-challenge-local
    ports:
      - "9000:8000"
    #platform: linux/amd64
    build:
      target: builder_image
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        # See: https://github.com/wemake-services/wemake-django-template/issues/1518
        USER_ID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    volumes:
      - django-static-local:/var/www/django/static
      - django-logs-local:/var/www/log
    depends_on:
      - db-local
    networks:
      - pysect-network
    env_file:
      - ./docker/config/.env.local
    command: ./docker/django/local_run.sh

networks:
  pysect-network:
    external: true


volumes:
  pgdata-local:
  django-static-local:
  django-logs-local:
